<template>
  <div>
	<div class="select-main">
    <title-page
      title-text="Help me find a favorite IndyCar driver"
      />
		<div class="select-page">
      
      <div class="body-img">
        <img ref="image" 
          src="@/assets/IndycarLogo.png"
          alt="IndyCar Logo"
          contain
          class="logo-img"
          >
      </div>
      <div class="button55">
        <Btn @click="showModal()">Start</Btn>
        <Btn @click="showBios(randomDriver)">Random</Btn>
      </div>
		</div>
     <select-modal
      v-if="isModalVisible"
      :driver-data="driverData"
      :number-question="this.questionNumber"
      @close="closeModal"
      @end="showResults"
    />
    <bios
      v-if="this.isBiosVisible"
      :high-driver = this.highDriver
      :driver-bios = this.driverBios
      @close="closeBios"
    />
    <results
      v-if="this.isResultsVisible"
      @close="closeResults"
      @end="showBios"
      :three-drivers="this.threeDrivers"
    />	
	</div>	
</div>
</template>
  
<script>

  import SelectModal from './SelectModal'
  import Bios from '@/components/Selector/Bios'
  import Results from './Results'
  import TitlePage from '@/components/Partials/Title'
  import driversAnswers from "@/components/Helpers/driverData.json"
  import Btn from '@/components/Partials/Btn'


  export default {
	name: 'selector',
  components: {
    SelectModal,
    TitlePage,
    Bios,
    Results,
    Btn
    },
    data () {
	  return {
      isModalVisible: null,
      resultsTrack: [],
      currentDrivers: null,
      isBiosVisible: null,
      isResultsVisible: null,
      randomNumber: 0,
      questionNumber: 0,
      driverData: driversAnswers,
      driverBios: [
      {
          "Name": "Álex Palou",
          "Number": "10",
          "2025 Finish": "Champion",
          "Team": "Chip Ganassi Racing",
          "Country": "Spain",
          "Birthdate": "1997",
          "Championships": "'21, '23, '24, '25'",
          "Indy500s": "'25'",
          "Color": "yellow",
          "Summary": "Alex Palou won his 4th IndyCar championship in 5 years last season, cementing himself as one the all-time best with a long career still ahead of him. Palou also can finally call himself an Indy 500 winner after putting his face on the Borg Warner Trophy in 2025. By showing that he can win on ovals last season, Palou will be an even bigger favorite to win another championship in 2026.",
          "picnum": new URL('@/assets/Numbers/10Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/AlexPalouProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/ChipGanassiRacing.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Indianapolis Motor Speedway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Alex-Palou",
          "Twitter": "https://www.twitter.com/AlexPalou",
          "Instagram": "https://www.instagram.com/AlexPalou",
          "Facebook": "https://www.facebook.com/AlexPalouOfficial",
          "TikTok": "",
          "Twitch": "https://www.twitch.tv/alexpalou",
          "Youtube":"",
          "Shop": "https://shop.ims.com/collections/indycar-drivers-alex-palou"
        },
        {
          "Name": "Pato O'Ward",
          "Number": "5",
          "2025 Finish": "2nd",
          "Team": "Arrow McLaren",
          "Country": "Mexico",
          "Birthdate": "1999",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "#f78000",
          "Summary": "After a runner-up championship finish in 2025, Pato O'Ward remains one of IndyCar's top talents and the most popular driver in the paddock. The Mexican star won multiple races but watched Alex Palou claim yet another crown. With Arrow McLaren continuing to close the gap on Penske and Ganassi, O'Ward enters 2026 determined to finally break through for both the championship and an elusive Indy 500 victory after multiple heartbreaking near-misses.",
          "picnum": new URL('@/assets/Numbers/5Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/PatricioOwardProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/ArrowMcLaren.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Indianapolis Motor Speedway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Patricio-OWard",
          "Twitter": "https://www.twitter.com/patriciooward",
          "Instagram": "https://www.instagram.com/patriciooward",
          "Facebook": "https://www.facebook.com/PatricioOWard",
          "TikTok": "https://www.tiktok.com/@patriciooward",
          "Twitch": "",
          "Youtube":"https://www.youtube.com/@patricioowardofficial",
          "Shop": "https://shop.ims.com/collections/patricio-oward"
        },
         {
          "Name": "Scott Dixon",
          "Number": "9",
          "2025 Finish": "3rd",
          "Team": "Chip Ganassi Racing",
          "Country": "New Zealand",
          "Birthdate": "1980",
          "Championships": "'03, '08, '13, '15, '18, '20",
          "Indy500s": "'08",
          "Color": "orange",
          "Summary": "The legendary Kiwi showed he's still got it in 2025, finishing 3rd in the championship and proving age is just a number. With six IndyCar titles and one Indy 500 victory, Dixon continues to chase a 7th championship that would further cement his status as one of the all-time greats. At 45, the all-time lap leader at Indianapolis shows no signs of slowing down entering 2026.",
          "picnum": new URL('@/assets/Numbers/9Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/ScottDixonProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/ChipGanassiRacing.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | St Pete 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Scott-Dixon",
          "Twitter": "https://www.twitter.com/scottdixon9",
          "Instagram": "https://www.instagram.com/scottdixon9",
          "Facebook": "https://www.facebook.com/scottdixon",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"",
          "Shop": "https://shop.ims.com/collections/scott-dixon"
        },
        {
          "Name": "Kyle Kirkwood",
          "Number": "27",
          "2025 Finish": "4th",
          "Team": "Andretti Global",
          "Country": "USA",
          "Birthdate": "1998",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "pink",
          "Summary": "Kyle Kirkwood's breakout 2025 season saw him finish 4th in the championship with multiple wins, delivering on the immense promise he showed coming up the IndyCar ladder. The Florida native has emerged as Andretti Global's top driver and enters 2026 as a legitimate championship contender. Already one of the best on street courses, Kirkwood finally broke through on ovals last season and has looked like a legitimate contender at Indy where he'd love to write his name in the record books.",
          "picnum": new URL('@/assets/Numbers/27Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/KyleKirkwoodProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/AndrettiGlobal.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Indianapolis Motor Speedway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Kyle-Kirkwood",
          "Twitter": "https://twitter.com/KKirkwoodRacing",
          "Instagram": "https://www.instagram.com/Kyle_Kirkwood",
          "Facebook": "https://www.facebook.com/KyleKirkwoodRacing",
          "TikTok": "https://www.tiktok.com/@kyle_kirkwood",
          "Twitch": "",
          "Youtube":"",
          "Shop": "https://shop.ims.com/pages/search-results-page?q=Kirkwood"
        },
        {
          "Name": "Christian Lundgaard",
          "Number": "7",
          "2025 Finish": "5th",
          "Team": "Rahal Letterman Lanigan",
          "Country": "Denmark",
          "Birthdate": "2001",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "orange",
          "Summary": "Christian Lundgaard proved he belonged at Arrow McLaren in 2025, finishing 5th in the championship and establishing himself as a consistent frontrunner on road and street courses. The young Dane adapted quickly to his new team and finally challenged Pato O'Ward for team supremacy, but will need to improve on ovals to become a real championship contender in 2026.",
          "picnum": new URL('@/assets/Numbers/7Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/ChristianLundgaardProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/ArrowMcLaren.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | St Pete 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Christian-Lundgaard",
          "Twitter": "https://www.twitter.com/lundgaardoff",
          "Instagram": "https://www.instagram.com/lundgaardofficial",
          "Facebook": "https://www.facebook.com/lundgaardofficial",
          "TikTok": "https://www.tiktok.com/@lundgaardofficial",
          "Twitch": "https://www.twitch.tv/clundgaard30",
          "Youtube":"",
          "Shop": "https://shop.ims.com/pages/search-results-page?q=lundgaard"
        },
        {
          "Name": "Felix Rosenqvist",
          "Number": "60",
          "2025 Finish": "6th",
          "Team": "Meyer Shank Racing",
          "Country": "Sweden",
          "Birthdate": "1991",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "Pink",
          "Summary": "Felix Rosenqvist and Meyer Shank Racing continued their upward trajectory in 2025, with Felix finishing 6th in the championship, the best result in team history. The technical alliance with Chip Ganassi Racing has paid dividends, and the Swedish driver has rediscovered the form that made him a race winner earlier in his career. Rosenqvist enters 2026 hungry to get back into victory lane.",
          "picnum": new URL('@/assets/Numbers/60Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/FelixRosenqvistProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/MeyerShankRacing.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Indianapolis Motor Speedway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Felix-Rosenqvist",
          "Twitter": "https://www.twitter.com/FRosenqvist",
          "Instagram": "https://www.instagram.com/frosenqvist",
          "Facebook": "https://www.facebook.com/FelixRosenqvistOfficial",
          "Twitch": "",
          "Youtube":"",
          "Shop": "https://shop.ims.com/collections/indycar-drivers-felix-rosenqvist"
        },
        {
          "Name": "Marcus Armstrong",
          "Number": "66",
          "2025 Finish": "8th",
          "Team": "Meyer Shank Racing",
          "Country": "New Zealand",
          "Birthdate": "2000",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "pink",
          "Summary": "Marcus Armstrong found his footing in 2025 with Meyer Shank Racing, finishing 8th in the championship and earning his first podium on an oval. The young Kiwi benefited from the team's Ganassi alliance and proved he can compete at the front of the field. Armstrong enters 2026 looking to build on his breakthrough season and finally get to victory lane.",
          "picnum": new URL('@/assets/Numbers/66Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/MarcusArmstrongProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/MeyerShankRacing.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | World Wide Technology Raceway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Marcus-Armstrong",
          "Twitter": "https://www.twitter.com/MarcusArmstrng",
          "Instagram": "https://www.instagram.com/marcusarmstrong",
          "Facebook": "https://www.facebook.com/MarcusArmstrng",
          "TikTok": "",
          "Twitch": "",
          "Youtube": "https://www.youtube.com/@screamingmeals",
          "Shop": "https://shop.ims.com/pages/search-results-page?q=Ganassi"
        },
        {
          "Name": "Will Power",
          "Number": "26",
          "2025 Finish": "9th",
          "Team": "Andretti Global",
          "Country": "Australia",
          "Birthdate": "1981",
          "Championships": "'14, '22",
          "Indy500s": "'18",
          "Color": "red",
          "Summary": "Will Power made a move to Andretti Global for 2026 after spending almost his entire IndyCar career with Team Penske. The two-time champion finished 9th in an inconsistent 2025 season but remains one of the most talented drivers in the series. At 45, Power will be racing with a chip on his shoulder in 2026 feeling disrespected by his former team and motivated to prove he can still compete at the highest level.",
          "picnum": new URL('@/assets/Numbers/26Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/WillPowerProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/AndrettiGlobal.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Mid-Ohio 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Will-Power",
          "Twitter": "https://www.twitter.com/12WillPower",
          "Instagram": "https://www.instagram.com/12willpower",
          "Facebook": "https://www.facebook.com/willpower12",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"",
          "Shop": "https://shop.ims.com/collections/will-power"
        },
        {
          "Name": "Scott McLaughlin",
          "Number": "3",
          "2025 Finish": "10th",
          "Team": "Team Penske",
          "Country": "New Zealand",
          "Birthdate": "1993",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "yellow",
          "Summary": "Scott McLaughlin's 2025 season was one to forget. Team Penske faced penalties after Indy 500 qualifying, while McLaughlin's race ended before it began with a warm-up lap crash. One of the pre-season favorites finished a disappointing 10th, and both driver and team are eager to put 2025 behind them. Look for Scotty Mac to bounce back in 2026 and once again be a championship contender.",
          "picnum": new URL('@/assets/Numbers/3Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/ScottMcLaughlinProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/TeamPenske.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Indianapolis Motor Speedway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Scott-McLaughlin",
          "Twitter": "https://www.twitter.com/smclaughlin93",
          "Instagram": "https://www.instagram.com/smclaughlin93",
          "Facebook": "https://www.facebook.com/smclaughlin93",
          "TikTok": "",
          "Twitch": "https://www.twitch.tv/scottmclaughlin93",
          "Youtube":"https://www.youtube.com/playlist?list=PLO_0HVxzyH4MFglLkaUEyiw_om7UkDM_7",
          "Shop": "https://shop.ims.com/collections/scott-mclaughlin"
        },
        {
          "Name": "David Malukas",
          "Number": "12",
          "2025 Finish": "11th",
          "Team": "Team Penske",
          "Country": "USA",
          "Birthdate": "2001",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "red",
          "Summary": "David Malukas delivered a strong 2025 season with AJ Foyt Racing, finishing 11th in the championship. His performance was enough to earn him the much rumored full-time ride with Team Penske. Not everyone thinks Malukas has earned the opportunity with Penske, but he is determined to prove his critics wrong and insert himself into the championship mix in 2026. Already one of the top oval racers in the series, it seems inevitable that he will get a win eventually.",
          "picnum": new URL('@/assets/Numbers/12Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/DavidMalukasProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/TeamPenske.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | St Pete 2026",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/David-Malukas",
          "Twitter": "https://www.twitter.com/malukasdavid",
          "Instagram": "https://www.instagram.com/davidmalukas",
          "Facebook": "",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"https://www.youtube.com/@malukasdavid",
          "Shop": "https://shop.ims.com/collections/david-malukas"
        },
        {
          "Name": "Josef Newgarden",
          "Number": "2",
          "2025 Finish": "12th",
          "Team": "Team Penske",
          "Country": "USA",
          "Birthdate": "1990",
          "Championships": "'17, '19",
          "Indy500s": "'23, '24'",
          "Color": "#d21c2a",
          "Summary": "Josef Newgarden endured a difficult 2025 season alongside his Penske teammates, finishing 12th as the team struggled with consistency all season. The two-time champion and back-to-back Indy 500 winner capped off the tough season with a win though and hopes to carry that momentum into 2026.",
          "picnum": new URL('@/assets/Numbers/2Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/JosefNewgardenProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/TeamPenske.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Indianapolis Motor Speedway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Josef-Newgarden",
          "Twitter": "https://www.twitter.com/josefnewgarden",
          "Instagram": "https://www.instagram.com/josefnewgarden",
          "Facebook": "https://www.facebook.com/josefnewgarden",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"https://www.youtube.com/@JosefNewgarden",
          "Shop": "https://shop.ims.com/collections/josef-newgarden"
        },
        {
          "Name": "Christian Rasmussen",
          "Number": "21",
          "2025 Finish": "13th",
          "Team": "Ed Carpenter Racing",
          "Country": "Denmark",
          "Birthdate": "2000",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "blue",
          "Summary": "Christian Rasmussen took a significant step forward in 2025, finishing 13th in the championship anchored by his win at the Milwaukee Mile. The young Dane learned a lot from teammate Alexander Rossi and showed he belongs in the series, but still needs to be more consistent to become a real contender. Rasmussen enters 2026 hoping to build on his breakthrough win and prove it was no fluke.",
          "picnum": new URL('@/assets/Numbers/21Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/ChristianRasmussenProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/EdCarpenterRacing.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | St Pete 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Ed-Carpenter",
          "Twitter": "https://www.twitter.com/ChristianR_DK",
          "Instagram": "",
          "Facebook": "https://www.facebook.com/edcarpenterindy",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"",
          "Shop": "https://shop.ims.com/collections/indycar-drivers-ed-carpenter"
        },
         {
          "Name": "Rinus VeeKay",
          "Number": "76",
          "2025 Finish": "14th",
          "Team": "Juncos Holling Racing",
          "Country": "Netherlands",
          "Birthdate": "2000",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "green",
          "Summary": "Rinus VeeKay moves to Juncos Holling Racing in 2026, his 3rd different team in 3 years. Veekay has consistently outperformed expectations on smaller teams and hopes to get Juncos their first win in 2026. If the young Dutchman can impress in a Juncos car, he could finally be in for a better ride in 2027.",
          "picnum": new URL('@/assets/Numbers/76Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/RinusVeekayProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/JuncosHollinger.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | St Pete 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Rinus-VeeKay",
          "Twitter": "https://www.twitter.com/RinusVeeKay",
          "Instagram": "https://www.instagram.com/RinusVeeKay",
          "Facebook": "https://www.facebook.com/RinusVeeKay",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"https://www.youtube.com/@vankalmthoutauto",
          "Shop": "https://shop.ims.com/collections/rinus-veekay"
        },
         {
          "Name": "Alexander Rossi",
          "Number": "20",
          "2025 Finish": "15th",
          "Team": "Ed Carpenter Racing",
          "Country": "USA",
          "Birthdate": "1991",
          "Championships": "0",
          "Indy500s": "'16",
          "Color": "#4ac5f4",
          "Summary": "Alexander Rossi's first season with Ed Carpenter Racing in 2025 was solid if unspectacular, finishing 15th in the championship. The 2016 Indy 500 winner continues to search for consistent speed but remains dangerous at Indianapolis where ECR always brings competitive cars. Rossi enters 2026 hoping for a little more consistency and that his experience helps make ECR a consistent contender week to week.",
          "picnum": new URL('@/assets/Numbers/20Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/AlexanderRossiProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/EdCarpenterRacing.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Indianapolis Motor Speedway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Alexander-Rossi",
          "Twitter": "https://www.twitter.com/alexanderrossi",
          "Instagram": "https://www.instagram.com/alexanderrossi",
          "Facebook": "https://www.facebook.com/AlexanderRossi",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"https://www.youtube.com/@offtrackwithhinchandrossi6872",
          "Shop": "https://shop.ims.com/collections/indycar-drivers-alexander-rossi"
        },
        {
          "Name": "Santino Ferrucci",
          "Number": "14",
          "2025 Finish": "16th",
          "Team": "A.J. Foyt Enterprises",
          "Country": "USA",
          "Birthdate": "1998",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "orange",
          "Summary": "Santino Ferrucci had a challenging season for AJ Foyt Racing in 2025, finishing 16th in the championship after being 9th in 2024. The divisive American driver remains one of the most aggressive on the grid and continues to excite on ovals. Ferrucci enters 2026 still searching for that elusive first IndyCar win that would put legendary owner AJ Foyt back in victory lane.",
          "picnum": new URL('@/assets/Numbers/14Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/SantinoFerrucciProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/AJFoytRacing.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Indianapolis Motor Speedway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Santino-Ferrucci",
          "Twitter": "https://www.twitter.com/santinoferrucci",
          "Instagram": "https://www.instagram.com/santinoferrucci",
          "Facebook": "https://www.facebook.com/santinof1/",
          "TikTok": "https://www.tiktok.com/@santinoferrucci",
          "Twitch": "https://www.twitch.tv/santinoferrucci",
          "Youtube":"",
          "Shop": "https://santinoferrucci.com/shop/shop/"
        },
        {
          "Name": "Kyffin Simpson",
          "Number": "8",
          "2025 Finish": "17th",
          "Team": "Chip Ganassi Racing",
          "Country": "Cayman Islands",
          "Birthdate": "2004",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "blue",
          "Summary": "Kyffin Simpson showed steady improvement in his second full season, finishing 17th in the 2025 championship and earning his first podium. Learning from legendary teammates Scott Dixon and Alex Palou has accelerated the young Cayman Islander's development. Simpson enters 2026 with higher expectations as he looks to break into the top 15 and add more podiums.",
          "picnum": new URL('@/assets/Numbers/8Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/KyffinSimpsonProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/ChipGanassiRacing.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Indianapolis Motor Speedway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Ed-Carpenter",
          "Twitter": "https://www.twitter.com/kyffin_simpson",
          "Instagram": "",
          "Facebook": "https://www.facebook.com/edcarpenterindy",
          "TikTok": "https://www.tiktok.com/@kyffinsimpson",
          "Twitch": "",
          "Youtube":"",
          "Shop": "https://shop.ims.com/collections/indycar-drivers-ed-carpenter"
        },
        {
          "Name": "Graham Rahal",
          "Number": "15",
          "2025 Finish": "18th",
          "Team": "Rahal Letterman Lanigan",
          "Country": "USA",
          "Birthdate": "1989",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "orange",
          "Summary": "Graham Rahal and RLL continue to search for the speed that made him a contender earlier in his career. The second-generation driver finished 18th in 2025 as the team struggled for consistency. One of the most fan-friendly drivers in the paddock, Rahal enters 2026 hoping his family team can turn things around, especially during the Month of May.",
          "picnum": new URL('@/assets/Numbers/15Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/GrahamRahalProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/RahalLetterman.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Indianapolis Motor Speedway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Graham-Rahal",
          "Twitter": "https://www.twitter.com/grahamrahal",
          "Instagram": "https://www.instagram.com/grahamrahal",
          "Facebook": "https://www.facebook.com/GrahamRahal",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"",
          "Shop": "https://shop.ims.com/collections/indycar-drivers-graham-rahal"
        },
        {
          "Name": "Marcus Ericsson",
          "Number": "28",
          "2025 Finish": "20th",
          "Team": "Andretti Global",
          "Country": "Sweden",
          "Birthdate": "1990",
          "Championships": "0",
          "Indy500s": "'22",
          "Color": "blue",
          "Summary": "Marcus Ericsson continued to struggle in 2025, finishing 20th in the championship after a nightmare 2024 season. The 2022 Indy 500 winner showed he is still a contender at Indy where he crossed the line 2nd before being DQ'd for an illegal car. Ericsson enters 2026 looking to return to the form that saw him win IndyCar's biggest race and compete for podiums and race wins.",
          "picnum": new URL('@/assets/Numbers/28Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/MarcusEricssonProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/AndrettiGlobal.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | St Pete 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Marcus-Ericsson",
          "Twitter": "https://www.twitter.com/ericsson_marcus",
          "Instagram": "https://www.instagram.com/ericsson_marcus",
          "Facebook": "https://www.facebook.com/MarcusEricssonOfficialF1Page",
          "TikTok": "https://www.tiktok.com/@ericsson_marcus",
          "Twitch": "",
          "Youtube":"https://www.youtube.com/@marcusericsson3800",
          "Shop": "https://shop.ims.com/collections/marcus-ericsson"
        },
        {
          "Name": "Nolan Siegel",
          "Number": "6",
          "2025 Finish": "22nd",
          "Team": "Arrow McClaren",
          "Country": "USA",
          "Birthdate": "2004",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "#4ac5f4",
          "Summary": "Nolan Siegel's first full season with Arrow McLaren in 2025 was a learning experience, finishing 22nd in the championship. The young American showed speed at times but struggled with consistency as he adapted to the demands of a full IndyCar season. Siegel enters 2026 with valuable experience under his belt but high expectations. Siegel will need to take a big step forward in his sophomore season to keep his seat at Arrow McLaren.",
          "picnum": new URL('@/assets/Numbers/6Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/NolanSiegelProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/ArrowMclaren.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | Long Beach 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Nolan-Siegel",
          "Twitter": "https://twitter.com/nolan_siegel",
          "Instagram": "https://www.instagram.com/nolansiegel",
          "Facebook": "https://www.facebook.com/NolanSiegelOfficial",
          "Twitch": "",
          "TikTok": "",
          "Youtube":"https://www.youtube.com/channel/UC03XUPVw0P9N4qZsO-UNDBw",
          "Shop": "https://shop.indycar.com/search?q=siegel"
        },
        {
          "Name": "Louis Foster",
          "Number": "45",
          "2025 Finish": "23rd",
          "Team": "Rahal Letterman Lanigan",
          "Country": "United Kingdom",
          "Birthdate": "2003",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "red",
          "Summary": "Louis Foster impressed at times during his rookie campaign, earning a pole in his rookie season. The young Brit will need to show more consistency in 2026 to prove he can become a mainstay in the series. With RLL making a big splahs with some signings in their garage, Foster should have some improved equipment to work with in 2026 and will be looking to take a step forward.",
          "picnum": new URL('@/assets/Numbers/45Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/LouisFosterProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/RahalLetterman.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | St Pete 2026",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Louis-Foster",
          "Twitter": "https://www.twitter.com/_LouisFoster",
          "Instagram": "https://www.instagram.com/_LouisFoster",
          "Facebook": "https://www.facebook.com/_LouisFoster",
          "Twitch": "https://www.twitch.tv/_LouisFoster",
          "Youtube":"",
          "Shop": "https://www.juncoshollinger.com/shop/"
        },
        {
          "Name": "Sting Ray Robb",
          "Number": "77",
          "2025 Finish": "25th",
          "Team": "Juncos Hollinger Racing",
          "Country": "USA",
          "Birthdate": "2001",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "orange",
          "Summary": "Sting Ray Robb had another tough season in 2025, but did get a top 10 finish at Long Beach. The young American driver has yet to find his footing in IndyCar, but gets a chance to come back with the same team for the first time in his career. Sting Ray enteres 2026 with optimism that he can finally quiet his critics and show that he belongs in the series.",
          "picnum": new URL('@/assets/Numbers/77Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/StingRayRobbProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/JuncosHollinger.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | World Wide Technology Raceway 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Sting-Ray-Robb",
          "Twitter": "https://www.twitter.com/sting_ray_robb",
          "Instagram": "https://www.instagram.com/sting_ray_robb",
          "Facebook": "https://www.facebook.com/stingrayrobbracing",
          "TikTok": "",
          "Twitch": "",
          "YouTube": "https://www.youtube.com/@stingrayrobb51",
          "Shop": "https://shop.ims.com/pages/indycar-homepage"
        },
        {
          "Name": "Romain Grosjean",
          "Number": "18",
          "2025 Finish": "N/A",
          "Team": "Dale Coyne Racing",
          "Country": "France/Switzerland",
          "Birthdate": "1986",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "#4ac5f4",
          "Summary": "Romain Grosjean is back with Dale Coyne Racing for the 2026 season after being unable to secure a ride in 2025. Grosjean has shown glimpses of brilliance throughout his IndyCar career, but has yet to breakthrough with a win or put together a complete season. The Phoenix goes back to where his IndyCar career started and hopes to find the joy in racing that he seemed to have when first joining the series.",
          "picnum": new URL('@/assets/Numbers/18Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/RomainGrosjeanProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/DaleCoyneRacing.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | St Pete 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Romain-Grosjean",
          "Twitter": "https://www.twitter.com/RGrosjean",
          "Instagram": "https://www.instagram.com/grosjeanromain",
          "Facebook": "https://www.facebook.com/grosjeanromain",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"https://www.youtube.com/@RomainGrosjean8",
          "Shop": "https://shop.ims.com/collections/romain-grosjean"
        },
        {
          "Name": "Dennis Hauger",
          "Number": "19",
          "2025 Finish": "Rookie",
          "Team": "Dale Coyne Racing",
          "Country": "Norway",
          "Birthdate": "2001",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "blue",
          "Summary": "Dennis Hauger begins his IndyCar career with high expectations after dominating the IndyNXT championship in 2025. The Norwegian Nightmare is tabbed for a potential Andretti Global ride in the future but will first need to prove the talent he showed in IndyNXT can translate to the top level. A win in 2026 is probably unlikely, but some top 10s and maybe top 5s should be in reach. Hauger would likely be disappointed in anything less than Rookie of the Year honors in 2026.",
          "picnum": new URL('@/assets/Numbers/19Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/DennisHaugerProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/DaleCoyneRacing.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | St Pete 2026",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Dennis-Hauger",
          "Twitter": "https://www.twitter.com/dennishauger",
          "Instagram": "https://www.instagram.com/dennishauger",
          "Facebook": "https://www.facebook.com/dennishauger",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"",
          "Shop": "https://shop.ims.com/collections/indycar-drivers-dennis-hauger"
        },
        {
          "Name": "Mick Schumacher",
          "Number": "47",
          "2025 Finish": "Rookie",
          "Team": "Arrow McLaren",
          "Country": "Germany",
          "Birthdate": "1999",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "#4ac5f4",
          "Summary": "Son of the legendary Michael Schumacher, Mick Schumacher will make the jump to IndyCar in 2026 with Rahal Letterman Lanigan Racing. The young German driver won an F2 championship before a short and difficult stint with Haas in Formula 1. Schumacher is eager to prove himself in IndyCar and hopes to find a long term home in the series. Expectations will be realistic in his rookie season as he faces ovals for the first time, but some top 10s and rookie of the year should be in reach.", 
          "picnum": new URL('@/assets/Numbers/47Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/MickSchumacherProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/ArrowMcLaren.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | St Pete 2024",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Mick-Schumacher",
          "Twitter": "https://www.twitter.com/mickschumacher",
          "Instagram": "https://www.instagram.com/mickschumacher",
          "Facebook": "https://www.facebook.com/MickSchumacher",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"https://www.youtube.com/@MickSchumacher",
          "Shop": "https://shop.ims.com/collections/indycar-drivers-mick-schumacher" 
        },
        {
          "Name": "Caio Collet",
          "Number": "4",
          "2025 Finish": "Rookie",
          "Team": "AJ Foyt Enterprises",
          "Country": "Brazil",
          "Birthdate": "2002",
          "Championships": "0",
          "Indy500s": "0",
          "Color": "pink",
          "Summary": "Caio Collet moves up to IndyCar in 2026 after a strong season in IndyNXT where he finished 2nd in the championship with 3 victories. The young Brazilian hopes to be the next great driver from Brazil that has struggled to produce another consistent star since Castroneves and Kanaan stepped away from the series full-time. Expectations for Collet will be realistic in his rookie season, driving for a team that hasn't won in over a decade, but rookie of the year isn't out of reach with a consistent season.",
          "picnum": new URL('@/assets/Numbers/4Number.png', import.meta.url),
          "biopic": new URL('@/assets/Drivers/CaioColletProfileBlur.jpeg', import.meta.url),
          "teampic": new URL('@/assets/Teams/AJFoytRacing.png', import.meta.url),
          "picref": "Photo credit: Nathan Reese | St Pete 2025",
          "Profile": "https://www.indycar.com/Series/IndyCar-Series/Caio-Collet",
          "Twitter": "https://www.twitter.com/caio_collet",
          "Instagram": "https://www.instagram.com/caio_collet",
          "Facebook": "https://www.facebook.com/caio.collet",
          "TikTok": "",
          "Twitch": "",
          "Youtube":"",
          "Shop": "https://shop.ims.com/collections/indycar-drivers-caio-collet" 
        },
        // {
        //   "Name": "Conor Daly",
        //   "Number": "76",
        //   "2025 Finish": "26th",
        //   "Team": "Juncos Hollinger Racing",
        //   "Country": "USA",
        //   "Birthdate": "1991",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "green",
        //   "Summary": "Conor Daly will drive for Juncos Hollinger Racing in 2025 after filling in for the team last year to help secure a top 22 position in the standings and the team he won a Star Mazda championship with way back in 2010. The popular Hoosier has become one the most vocal proponents of IndyCar, using his Speed Street podcast as his platform. Daly, a native Hoosier, is coming off 3 top 10 finishes and a lot of laps led the last 4 years at the Indy 500..",
        //   "picnum": new URL('@/assets/Numbers/76Number.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/ConorDalyProfileBlur.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/JuncosHollinger.png', import.meta.url),
        //   "picref": "Photo credit: Nathan Reese | World Wide Technology Raceway 2024",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Romain-Grosjean",
        //   "Twitter": "https://www.twitter.com/RGrosjean",
        //   "Instagram": "https://www.instagram.com/grosjeanromain",
        //   "Facebook": "https://www.facebook.com/grosjeanromain",
        //   "TikTok": "https://www.tiktok.com/@grosjeanromain8",
        //   "Twitch": "https://www.twitch.tv/grosjeanromain",
        //   "Youtube":"https://www.youtube.com/@RomainGrosjean8",
        //   "Shop": "https://shop.ims.com/collections/romain-grosjean"
        // },
        // {
        //   "Name": "Callum Ilott",
        //   "Number": "90",
        //   "2025 Finish": "33rd",
        //   "Team": "Prema Racing",
        //   "Country": "United Kingdom",
        //   "Birthdate": "1998",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "orange",
        //   "Summary": "After spending most of the 2024 IndyCar season on the sidelines outside of a few fill-in appearances with McLaren, Callum Ilott returns full-time with the new Prema Racing team. Prema, a highly successful F1 ladder team, is placing a lot of trust in Ilott to lead their new team alongside rookie, Robert Shwartzman. Ilott showed a lot of promise in previous seasons with Juncos and should be a fun story to watch in 2025, but a little patience might be needed before the team starts competing for wins.",
        //   "picnum": new URL('@/assets/Numbers/90Number.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/CallumIlottProfileBlur.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/PremaRacing.png', import.meta.url),
        //   "picref": "Photo credit: Nathan Reese | St Pete 2025",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Callum-Ilott",
        //   "Twitter": "https://www.twitter.com/Callum_Ilott",
        //   "Instagram": "https://www.instagram.com/Callum_Ilott",
        //   "Facebook": "https://www.facebook.com/Callumilottracing",
        //   "Twitch": "https://www.twitch.tv/callum_ilott",
        //   "Youtube":"",
        //   "Shop": "https://www.juncoshollinger.com/shop/"
        // },
        // {
        //   "Name": "Robert Shwartzman",
        //   "Number": "83",
        //   "2025 Finish": "Rookie",
        //   "Team": "Prema Racing",
        //   "Country": "Russia/Israel",
        //   "Birthdate": "1999",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "green",
        //   "Summary": "The Ferrari reserve driver is making the switch to IndyCar this season after spending a year in the top class of WEC with Ferrari. Shwartzman aims to secure Rookie of the Year honors with Prema Racing, a team he knows well from his three years competing with them in F3 and F2. However, with ovals being completely new to Schwartzman and driving for a new team in the series, the challenge will not be easy.",
        //   "picnum": new URL('@/assets/Numbers/83Number.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/RobertShwartzmanProfileBlur.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/PremaRacing.png', import.meta.url),
        //   "picref": "Photo credit: Nathan Reese | St Pete 2025",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Callum-Ilott",
        //   "Twitter": "https://www.twitter.com/ShwartzmanRob",
        //   "Instagram": "https://www.instagram.com/Callum_Ilott",
        //   "Facebook": "https://www.facebook.com/Callumilottracing",
        //   "Twitch": "https://www.twitch.tv/callum_ilott",
        //   "Youtube":"",
        //   "Shop": "https://www.juncoshollinger.com/shop/"
        // },
        //  {
        //   "Name": "Devlin DeFrancesco",
        //   "Number": "30",
        //   "2025 Finish": "N/A",
        //   "Team": "Rahal Letterman Lanigan",
        //   "Country": "Canada",
        //   "Birthdate": "2000",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "orange",
        //   "Summary": "After spending a year on the sidelines, DeFrancesco returns to IndyCar with RLL in 2025. The young Canadian had a couple of forgettable seasons with Andretti, but hopes to make some strides this season and prove he deserves to stick around. Don't expect DeFrancesco to contend for any wins this season, but if you like an underdog he certainly fits that criteria. A realistic goal for Devlin will be a top 20 finish in the season standings.",
        //   "picnum": new URL('@/assets/Numbers/30Number.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/DevlinDeFrancescoBlur.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/RahalLetterman.png', import.meta.url),
        //   "picref": "Photo credit: Joe Skibinski | Indycar.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Devlin-DeFrancesco",
        //   "Twitter": "https://www.twitter.com/DevlinDeFran",
        //   "Instagram": "https://www.instagram.com/devlindefran",
        //   "Facebook": "https://www.facebook.com/devlindefran",
        //   "Twitch": "",
        //   "Youtube":"",
        //   "Shop": "https://shop.ims.com/pages/search-results-page?q=Devlin"
        // },
        // {
        //   "Name": "Jacob Abel",
        //   "Number": "51",
        //   "2025 Finish": "Rookie",
        //   "Team": "Dale Coyne Racing",
        //   "Country": "USA",
        //   "Birthdate": "2001",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "red",
        //   "Summary": "Jacob Abel joins Dale Coyne Racing for his rookie season in IndyCar. The 2024 IndyNXT runner-up won 3 races but couldn't hold off a dominant Louis Foster, with whom he will continue his rivalry with in IndyCar as they both battle for rookie of the year. The Louisville, Kentucky native showed a lot of promise scoring 10 podiums last season in IndyNXT but might be in for a challenging rookie season with the underdog Dale Coyne Racing. A good season for Abel will include consistent clean runs with some top 10-15 finishes that he can build on for the future.",
        //   "picnum": new URL('@/assets/Numbers/51Number.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/JacobAbelProfileBlur.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/DaleCoyneRacing.png', import.meta.url),
        //   "picref": "Photo credit: Nathan Reese | Road America 2024",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Rinus-VeeKay",
        //   "Twitter": "https://www.twitter.com/RinusVeeKay",
        //   "Instagram": "https://www.instagram.com/RinusVeeKay",
        //   "Facebook": "https://www.facebook.com/RinusVeeKay",
        //   "TikTok": "",
        //   "Twitch": "",
        //   "Youtube":"https://www.youtube.com/@vankalmthoutauto",
        //   "Shop": "https://shop.ims.com/collections/rinus-veekay"
        // },
        // {
        //   "Name": "Toby Sowery",
        //   "Number": "51",
        //   "2025 Finish": "32nd",
        //   "Team": "Dale Coyne Racing",
        //   "Country": "United Kingdom",
        //   "Birthdate": "1996",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "orange",
        //   "Summary": "Toby Sowery made his long awaited debut ",
        //   "picnum": new URL('@/assets/Numbers/51Number.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/TobySoweryProfileBlur.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/DaleCoyneRacing.png', import.meta.url),
        //   "picref": "Photo credit: Nathan Reese | St Pete 2024",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Rinus-VeeKay",
        //   "Twitter": "https://www.twitter.com/RinusVeeKay",
        //   "Instagram": "https://www.instagram.com/RinusVeeKay",
        //   "Facebook": "https://www.facebook.com/RinusVeeKay",
        //   "TikTok": "",
        //   "Twitch": "",
        //   "Youtube":"https://www.youtube.com/@vankalmthoutauto",
        //   "Shop": "https://shop.ims.com/collections/rinus-veekay"
        // },
        // {
        //   "Name": "Romain Grosjean",
        //   "Number": "77",
        //   "2025 Finish": "13th",
        //   "Team": "Juncos Hollinger Racing",
        //   "Country": "France",
        //   "Birthdate": "1986",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "green",
        //   "Summary": "After an impressive start in 2023, Grosjean looked like a legit threat to contend for a title. Several potential wins ended in crashes for Grosjean and the season went south. The former F1 star moves over to Juncos Hollinger in 2024 where he'll once again be thrown into an underdog role. Can Romain be the driver to finally put Juncos in IndyCar victory lane? Whatever the result, this will be one of the fun stories to watch in 2024.",
        //   "picnum": new URL('@/assets/Numbers/77Number.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/RomainGrosjeanProfile.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/JuncosHollinger.png', import.meta.url),
        //   "picref": "Photo credit: Chris Jones | Indycar.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Romain-Grosjean",
        //   "Twitter": "https://www.twitter.com/RGrosjean",
        //   "Instagram": "https://www.instagram.com/grosjeanromain",
        //   "Facebook": "https://www.facebook.com/grosjeanromain",
        //   "TikTok": "https://www.tiktok.com/@grosjeanromain8",
        //   "Twitch": "https://www.twitch.tv/grosjeanromain",
        //   "Youtube":"https://www.youtube.com/@RomainGrosjean8",
        //   "Shop": "https://shop.ims.com/collections/romain-grosjean"
        // },
        // {
        //   "Name": "Agustín Canapino",
        //   "Number": "78",
        //   "2025 Finish": "21st",
        //   "Team": "Juncos Hollinger Racing",
        //   "Country": "Argentina",
        //   "Birthdate": "1990",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "orange",
        //   "Summary": "Canapino surprised a lot of people jumping into an open wheel car from Argentinan touring cars and staying relatively competitive with the rest of the field. He will be joined in 2024 at Juncos by Romain Grosjean, who will bring a lot of experience to the team. But after some team drama in 2023 for both drivers, everyone will be watching if the teammates get together on track.",
        //   "picnum": new URL('@/assets/Numbers/CanapinoNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/AgustinCanapinoProfile.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/JuncosHollinger.png', import.meta.url),
        //   "picref": "Photo credit: Nathan Reese | St Pete 2024",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Agustin-Canapino",
        //   "Twitter": "https://www.twitter.com/AgustinCanapino",
        //   "Instagram": "https://www.instagram.com/agustincanapino",
        //   "Facebook": "https://www.facebook.com/AgustinCanapinoSitioOficial",
        //   "TikTok": "https://www.tiktok.com/@agustincanapinooficial",
        //   "Twitch": "https://www.twitch.tv/agustincanapino",
        //   "Youtube":"",
        //   "Shop": "https://www.juncoshollinger.com/shop/"
        // },
        // {
        //   "Name": "Ed Carpenter",
        //   "Number": "20",
        //   "2025 Finish": "30th",
        //   "Team": "Ed Carpenter Racing",
        //   "Country": "USA",
        //   "Birthdate": "1981",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "blue",
        //   "Summary": "One of the last throwbacks to the oval only IRL days, Ed is also the only owner/driver left in the series. Ed will run the #20 on ovals, splitting the ride with rookie Christian Rasmussen who will run the road and street courses in the car. As an Indy native, an Ed Carpenter Indy 500 win would be a popular one, and he will likely keep trying as long as he's competitive.",
        //   "picnum": new URL('@/assets/Numbers/CarpenterNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/EdCarpenterProfile.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/EdCarpenterRacing.png', import.meta.url),
        //   "picref": "Photo credit: Chris Owens | Indycar.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Ed-Carpenter",
        //   "Twitter": "https://www.twitter.com/edcarpenter20",
        //   "Instagram": "",
        //   "Facebook": "https://www.facebook.com/edcarpenterindy",
        //   "TikTok": "",
        //   "Twitch": "",
        //   "Youtube":"",
        //   "Shop": "https://shop.ims.com/collections/indycar-drivers-ed-carpenter"
        // },
        // {
        //   "Name": "Linus Lundqvist",
        //   "Number": "8",
        //   "2025 Finish": "Rookie",
        //   "Team": "Chip Ganassi Racing",
        //   "Country": "Sweden",
        //   "Birthdate": "1999",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "blue",
        //   "Summary": "The 2022 IndyNXT champion was on the outside looking in when the silly season musical chairs stopped ahead of last season. He eventually got a shot after an injury to Simon Pagenaud and the Swede was so impressive that he was hired by Chip Ganassi to replace his fellow countryman, Marcus Ericsson, in the #8 car for 2024. The expectations will be high considering Lundqvist is a rookie, but not many would be shocked to see him score a victory at some point this season.",
        //   "picnum": new URL('@/assets/Numbers/LundqvistNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/LinusLundqvistProfile.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/ChipGanassiRacing.png', import.meta.url),
        //   "picref": "Photo credit: Nathan Reese | indycardrivers.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Ed-Carpenter",
        //   "Twitter": "https://www.twitter.com/edcarpenter20",
        //   "Instagram": "",
        //   "Facebook": "https://www.facebook.com/edcarpenterindy",
        //   "TikTok": "",
        //   "Twitch": "",
        //   "Youtube":"",
        //   "Shop": "https://shop.ims.com/collections/indycar-drivers-ed-carpenter"
        // },
        // {
        // {
        //   "Name": "Pietro Fittipaldi",
        //   "Number": "30",
        //   "2025 Finish": "N/A",
        //   "Team": "Rahal Letterman Lanigan",
        //   "Country": "USA/Brazil",
        //   "Birthdate": "1996",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "red",
        //   "Summary": "Fittipaldi has taken a wild path to landing a solid full time IndyCar seat. The grandson of F1 and IndyCar legend Emerson Fittipaldi, Pietro has been in the NASCAR Whelen series, multiple stints in IndyCar with Dale Coyne, F1, and Stock Car Brazil among others. While not technically a rookie, this will be Pietro's first full IndyCar season where he'll join Rahal Letterman Lanigan. He should be a fun driver to keep an eye on to see if he can establish himself as a serious long term contender in IndyCar.",
        //   "picnum": new URL('@/assets/Numbers/FittipaldiNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/PietroFittipaldiProfile.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/RahalLetterman.png', import.meta.url),
        //   "picref": "Photo credit: James Black | Indycar.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Pietro-Fittipaldi",
        //   "Twitter": "https://www.https://twitter.com/PiFitti",
        //   "Instagram": "https://www.instagram.com/pifitti",
        //   "Facebook": "",
        //   "TikTok": "https://www.tiktok.com/@fittibros",
        //   "Twitch": "https://www.twitch.tv/fittipaldibrothers",
        //   "Youtube":"https://www.youtube.com/@FittipaldiBrothers",
        //   "Shop": "https://shop.indycar.com/search?q=fittipaldi"
        // },
        // {
        //   "Name": "Dale Coyne TBD",
        //   "Number": "18",
        //   "2025 Finish": "N/A",
        //   "Team": "Dale Coyne Racing",
        //   "Country": "Parts Unknown",
        //   "Birthdate": "2000",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "orange",
        //   "Summary": "This is a driver that everyone can agree will be a big underdog this season and is really looking to establish themselves in IndyCar. With little to no testing this offseason and agreeing to a last minute part-time deal, it won't be easy but everyone loves an underdog and will be hoping to see them make the most of their ride with Dale Coyne.",
        //   "picnum": new URL('@/assets/Numbers/HarveyNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/UnknownDriver.png', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/DaleCoyneRacing.png', import.meta.url),
        //   "picref": "",
        //   "Profile": "https://www.indycar.com",
        //   "Twitter": "https://www.twitter.com/Indycar",
        //   "Instagram": "https://www.instagram.com/Indycar",
        //   "Facebook": "https://www.facebook.com/Indycar",
        //   "Twitch": "",
        //   "Youtube":"https://www.youtube.com/@IndyCar",
        //   "Shop": "https://shop.ims.com/"
        // },
        // {
        //   "Name": "Colin Braun",
        //   "Number": "51",
        //   "2025 Finish": "Rookie",
        //   "Team": "Dale Coyne Racing",
        //   "Country": "USA",
        //   "Birthdate": "1988",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "#4ac5f4",
        //   "Summary": "After a few junior open wheel championships, Colin Braun has spent the majority of his career racing and winning in the IMSA Weathertech series, but he's also competed in NASCAR and Rallycross. Braun will finally realize his dream of driving in IndyCar as he runs a part-time schedule with Dale Coyne. The 35 year old rookie will be a popular underdog as he tries to prove he belongs in the series.",
        //   "picnum": new URL('@/assets/Numbers/BraunNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/ColinBraun.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/CoynewithRWR.png', import.meta.url),
        //   "picref": "Photo credit: Joe Skibinski | Indycar.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Colin-Braun",
        //   "Twitter": "https://twitter.com/colinbraun",
        //   "Instagram": "https://www.instagram.com/colinbraun",
        //   "Facebook": "https://www.facebook.com/ColinBraun/",
        //   "Twitch": "",
        //   "TikTok": "",
        //   "Youtube":"",
        //   "Shop": "https://shop.indycar.com/search?q=braun"
        // },
        //  {
        //   "Name": "Jack Harvey",
        //   "Number": "18",
        //   "2025 Finish": "24th",
        //   "Team": "Dale Coyne Racing",
        //   "Country": "United Kingdom",
        //   "Birthdate": "1993",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "orange",
        //   "Summary": "After being dropped by RLL late in the 2023 season, Jack Harvey was left without a full-time ride for 2024. He was able to secure a part-time ride with Dale Coyne Racing where he will drive 14 races and hope to show some of the promise he did with Meyer Shank Racing to prove he still belongs in the series.",
        //   "picnum": new URL('@/assets/Numbers/HarveyNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/JackHarveyProfile.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/DaleCoyneRacing.png', import.meta.url),
        //   "picref": "Photo credit: James Black | Indycar.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Jack-Harvey",
        //   "Twitter": "https://www.twitter.com/jack_harvey42",
        //   "Instagram": "https://www.instagram.com/jack_harvey42",
        //   "Facebook": "https://www.facebook.com/JackHarveyRacing",
        //   "Twitch": "",
        //   "Youtube":"https://www.youtube.com/@JackHarvey42",
        //   "Shop": "https://shop.ims.com/collections/jack-harvey"
        // },
        // {
        //   "Name": "Théo Pourchaire",
        //   "Number": "6",
        //   "2025 Finish": "Rookie",
        //   "Team": "Arrow McLaren Racing",
        //   "Country": "France",
        //   "Birthdate": "2003",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "orange",
        //   "Summary": "The reigning F2 champion steps into the #6 Arrow McLaren ride after David Malukas was released drom the team due to injury. Other than the Indy 500, the Frenchman will finish out the season for the team and hope to impress enough to get an offer beyond this season. Théo may still have an eye on F1 though as he remains a reserve driver for Alfa Romeo.",
        //   "picnum": new URL('@/assets/Numbers/PourchaireNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/TheoPourchaireProfile.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/ArrowMcLaren.png', import.meta.url),
        //   "picref": "Photo credit: Nathan Reese | indycardrivers.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Theo-Pourchaire",
        //   "Twitter": "https://twitter.com/TPourchaire",
        //   "Instagram": "https://www.instagram.com/theopourchaire21/?hl=en",
        //   "Facebook": "https://www.facebook.com/TheoPourchaire/",
        //   "TikTok": "https://www.tiktok.com/@theopourchaire21?",
        //   "Twitch": "",
        //   "Youtube":"",
        //   "Shop": "https://shop.ims.com/collections/theo-pourchaire"
        // },
        // {
        //   "Name": "Hélio Castroneves",
        //   "Number": "06",
        //   "2025 Finish": "18th",
        //   "Team": "Meyer Shank Racing",
        //   "Country": "Brazil",
        //   "Birthdate": "1975",
        //   "Championships": "0",
        //   "Indy500s": "'01, '02, '09, '21",
        //   "Color": "pink",
        //   "Summary": "After four seasons running a part time schedule, the four time Indy 500 champ came back to run a full schedule with MSR last season with disappointing results. Hélio and MSR won the 2021 Indy 500 and won the 24 Hours of Daytona together the last two seasons.",
        //   "picnum": new URL('@/assets/Numbers/HelioNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/HelioCastroneves.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/MeyerShankRacing.png', import.meta.url),
        //   "picref": "Photo credit: Joe Skibinski | Indycar.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Helio-Castroneves",
        //   "Twitter": "https://www.twitter.com/h3lio",
        //   "Instagram": "https://www.instagram.com/heliocastroneves",
        //   "Facebook": "https://www.facebook.com/h3lio",
        //   "Twitch": "",
        //   "Youtube":"",
        //   "Shop": "https://shop.ims.com/collections/indycar-drivers-helio-castroneves"
        // },
        // {
        //   "Name": "Simona De Silvestro",
        //   "Number": "16",
        //   "2025 Finish": "32nd",
        //   "Team": "Paretta Autosport",
        //   "Country": "Switzerland",
        //   "Birthdate": "1988",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "orange",
        //   "Summary": "Simona returned to a part-time IndyCar schedule recently after being out of IndyCar completely for five years. Probably the best female road course racer in IndyCar history, she will be driving for Paretta Autosports with ECR on select road and street courses in 2023.",
        //   "picnum": new URL('@/assets/Numbers/DesilvestroNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/SimonaDeSilvestro.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/ParettaAutosport.png', import.meta.url),
        //   "picref": "Photo credit: Joe Skibinski | Indycar.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Simona-de-Silvestro",
        //   "Twitter": "https://www.twitter.com/simdesilvestro",
        //   "Instagram": "https://www.instagram.com/simonadesilvestro",
        //   "Facebook": "https://www.facebook.com/simdesilvestro",
        //   "Twitch": "",
        //   "Youtube":"",
        //   "Shop": "https://shop.ims.com/collections/simona-de-silvestro"
        // },
        // {
        //   "Name": "Benjamin Pedersen",
        //   "Number": "55",
        //   "2025 Finish": "Rookie",
        //   "Team": "A.J. Foyt Enterprises",
        //   "Country": "Denmark",
        //   "Birthdate": "1999",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "orange",
        //   "Summary": "Pedersen will move up to IndyCar from IndyNXT (former Indy Lights) in 2023, where he scored his first win late in the season at Portland. He will race the #55 alongside Ferrucci at AJ Foyt Racing, and will look to win \"Rookie of the Year\".",
        //   "picnum": new URL('@/assets/Numbers/PedersonNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/BenjaminPedersen.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/AJFoytRacing.png', import.meta.url),
        //   "picref": "Photo credit: Travis Hinkle | Indycar.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Benjamin-Pedersen",
        //   "Twitter": "https://www.twitter.com/BPedersen_55",
        //   "Instagram": "https://www.instagram.com/benjaminpedersen_55/",
        //   "Facebook": "https://www.facebook.com/benjaminpedersen24",
        //   "Twitch": "",
        //   "Youtube":"",
        //   "Shop": "https://shop.ims.com/pages/search-results-page?q=foyt"
        // },
        // {
        //   "Name": "Simon Pagenaud",
        //   "Number": "60",
        //   "2025 Finish": "15th",
        //   "Team": "Meyer Shank Racing",
        //   "Country": "France",
        //   "Birthdate": "1984",
        //   "Championships": "'16",
        //   "Indy500s": "'19",
        //   "Color": "",
        //   "Summary": "In his first season at Meyer Shank Racing, the former IndyCar champ had a decent first half before struggling the last seven races. Pagenaud and MSR have won the 24 Hours of Daytona together the last two seasons, and hope to bring the same success to the IndyCar side in 2023.",
        //   "picnum": new URL('@/assets/Numbers/PagenaudNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/SimonPagenaud.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/MeyerShankRacing.png', import.meta.url),
        //   "picref": "Photo credit: Joe Skibinski | Indycar.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Simon-Pagenaud",
        //   "Twitter": "https://www.twitter.com/simonpagenaud",
        //   "Instagram": "https://www.instagram.com/simonpagenaud",
        //   "Facebook": "https://www.facebook.com/simonpagenaud",
        //   "Twitch": "",
        //   "Youtube":"",
        //   "Shop": "https://shop.ims.com/collections/simon-pagenaud"
        // },
        // {
        //   "Name": "Takuma Sato",
        //   "Number": "11",
        //   "2025 Finish": "19th",
        //   "Team": "Chip Ganassi Racing",
        //   "Country": "Japan",
        //   "Birthdate": "1977",
        //   "Championships": "0",
        //   "Indy500s": "'17, '20",
        //   "Color": "orange",
        //   "Summary": "The two-time Indy 500 Champion will scale back his schedule in 2023, running the ovals for Chip Ganassi in the #11. Known for his motto \"No Attack, No Chance\", Sato's aggressive style has made him a polarizing figure in IndyCar but also earned him some big wins.",
        //   "picnum": new URL('@/assets/Numbers/SatoNumber.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/TakumaSato.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/ChipGanassiRacing.png', import.meta.url),
        //   "picref": "Photo credit: Joe Skibinski | Indycar.com",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Takuma-Sato",
        //   "Twitter": "https://www.twitter.com/TakumaSatoRacer",
        //   "Instagram": "https://www.instagram.com/takumasato_official",
        //   "Facebook": "",
        //   "Twitch": "",
        //   "Youtube":"",
        //   "Shop": "https://shop.ims.com/collections/takuma-sato"
        // }
        //  {
        //   "Name": "Colton Herta",
        //   "Number": "26",
        //   "2025 Finish": "2nd",
        //   "Team": "Andretti Global",
        //   "Country": "USA",
        //   "Birthdate": "2000",
        //   "Championships": "0",
        //   "Indy500s": "0",
        //   "Color": "#fce800",
        //   "Summary": "Colton Herta fell one spot short of winning an IndyCar championship in 2024, but he finished the season strong winning on an oval for the first time at Nashville Super Speedway. With his fast hands and knack for highlight reel qualifying laps, the son of Bryan Herta is one of the most popular young drivers in the sport. This could be Herta's last season in IndyCar for now as he's rumored to be in line for one of the Cadillac F1 seats in 2026.",
        //   "picnum": new URL('@/assets/Numbers/26Number.png', import.meta.url),
        //   "biopic": new URL('@/assets/Drivers/ColtonHertaProfileBlur.jpeg', import.meta.url),
        //   "teampic": new URL('@/assets/Teams/AndrettiGlobal.png', import.meta.url),
        //   "picref": "Photo credit: Nathan Reese | Nashville Super Speedway 2024",
        //   "Profile": "https://www.indycar.com/Series/IndyCar-Series/Colton-Herta",
        //   "Twitter": "https://www.twitter.com/ColtonHerta",
        //   "Instagram": "https://www.instagram.com/coltonherta",
        //   "Facebook": "https://www.facebook.com/ColtonHertaRacing",
        //   "TikTok": "",
        //   "Twitch": "https://www.twitch.tv/coltonherta",
        //   "Youtube":"",
        //   "Shop": "https://shop.ims.com/collections/driver_colton-herta"
        // }
      ]
    }
  },
  computed: {
      randomDriver() {
        this.randomNumber = Math.floor(Math.random() * this.driverData.length)
        const item = this.driverData[this.randomNumber]
        return item["name"]
      }
  },
  methods: {
    showModal() {
      this.driverData.forEach(driver => {
        driver["points"] = 0
      })
      this.questionNumber = 0 
      this.isModalVisible = true
      // this.currentDrivers = driverData
    },
    closeResults() {
      this.isResultsVisible = false
      this.driverData.forEach(driver => {
        driver["points"] = 0
      })
      this.questionNumber = 0      
    },
    showBios(highDriver) {
      this.isModalVisible = false;
      this.highDriver = highDriver
      this.isBiosVisible = true
      this.isResultsVisible = false
    },
    showResults(threeDrivers){
      console.log("THREE: ", threeDrivers)
        this.isModalVisible = false
        let driverNames = []

        threeDrivers.forEach( driver => (driverNames.push(driver["name"])))

        for (const key in threeDrivers) {  
          for (const key2 in this.driverBios) {
            if (threeDrivers[key]["name"] === this.driverBios[key2]["Name"]){
              this.driverBios[key2]["points"] = threeDrivers[key]["points"]
            }
          }
        }

        const finalDrivers = this.driverBios.filter(bio => driverNames.includes(bio["Name"]))
        finalDrivers.sort((a, b) => {
              return b.points - a.points})
        this.threeDrivers = finalDrivers
        this.isResultsVisible = true
      },
    closeModal() {
      this.isModalVisible = false
      this.randomNumber = null
      this.currentDrivers = driverData
      driverData.forEach(driver => {
        driver["points"] = 0
      })

    },
    closeBios() {
        this.isBiosVisible = false
        this.randomNumber = null
        this.currentDrivers = driverData
        driverData.forEach(driver => {
          driver["points"] = 0
        })
      },
  },
    // mounted(){
    //     axios
    //         .get('driverData.json')
    //         .then(response => (driverData = response.data))
    //    }
}
  </script>
  
  <style>
.select-main{
  text-align: center;
  font-family: Verdana;
}
.body-img{
  padding: auto;
  display: inline-flex;
  margin-top: 60px;
  margin-bottom: 30px;
  width: 100%
}
.select-page{
  width: 100% !important;
  display: flex;
  float: center;
  flex-direction: column;
}
.logo-img{
  height: calc(95px + 9vw);
  margin: auto;
}
  .button55{
    margin: 60px 0px 150px 0px;
  }
  </style>
  